### ISSUE TITLE
Post hook run when dcommit exit code non-zero?

### ISSUE THREAD

**Issue by geraintwhite** [rkitover/git-svn-hooks#4]
My post-svn-dcommit hook is triggered even when the svn-dcommit fails:

```
Can't create session: Unable to connect to a repository at URL : Unexpected server error 500 'Internal Server Error' at /usr/local/Cellar/git/2.15.1_1/libexec/git-core/git-svn line 1011.
```

Perhaps the post hooks should only run when the git svn command is successful.

**Comment by rkitover** [comment]
I fixed this, as well as another thing I've been meaning to fix before, but I don't have access to git-svn anymore, could you please check if everything works correctly for you?

**Comment by rkitover** [comment]
Just fixed an oversight in the new code, please try latest master.

**Comment by geraintwhite** [comment]
Thanks, that works now

**Comment by rkitover** [comment]
Great, thank you for testing!
